### ISSUE TITLE
Segfault when deleting last planet in list

### ISSUE THREAD

**Issue by bryan-lunt** [ChristopherRabotin/GMAT#5]
These lines will create a segfault. It might work better to reverse iterate for deletion.

https://github.com/ChristopherRabotin/GMAT/blob/829b7c2c3c7ea73d759c338e7051f92f4f2f6f43/src/base/solarsys/SolarSystem.cpp#L2216-L2221

**Comment by ChristopherRabotin** [comment]
Hi Bryan,

Thanks for the info. However, this is fork of GMAT is not maintained at
all. It only exists to allow for quickly searching through the GMAT code.
I'm not a maintainer of GMAT, but I write an open-source alternative in
Python and in Rust.

Hence, best would be to reproduce the bug and reach out to Steve Hughes and
his team on Source forge.

Thanks.
